Feature: As a user i should be able to increment the world to the next generation.
  This will iterate the game world to the next generation
  Scenario: Simple world that is moved one generation ahead with the return keu
    Given a world initialized from the input
    """
Generation 1:
4 8
........
....*...
...**...
........
    """
    When the return key is pressed
    Then the output should be
    """
Generation 2:
4 8
........
...**...
...**...
........
    """