Feature: As a user I should be able see a textual output of the game of life world
  and see which cells are dead and alive.
  Scenario: Simple world that is moved one generation ahead.
    Given a world initialized from the input
    """
Generation 1:
4 8
........
...**...
...**...
........
    """
    Then the output should be
    """
Generation 2:
4 8
........
...**...
...**...
........
    """